version: '3.0'
services:
  prod:
    image: artemetrics/artemetrics-prod
    container_name: 'artemetrics-prod'
    ports:
      - '3000:3000'
    volumes:
      - './:/usr/src/app/'
      - 'node_modules:/usr/src/app/node_modules'
    command: npm run dev
volumes:
  node_modules:
